[package]
name = "gossip-stdx-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }
gossip-stdx = { path = ".." }

[[bin]]
name = "fuzz_ring_buffer"
path = "fuzz_targets/fuzz_ring_buffer.rs"
doc = false

[[bin]]
name = "fuzz_inline_vec"
path = "fuzz_targets/fuzz_inline_vec.rs"
doc = false

[[bin]]
name = "fuzz_byte_slab"
path = "fuzz_targets/fuzz_byte_slab.rs"
doc = false

[[bin]]
name = "fuzz_spsc"
path = "fuzz_targets/fuzz_spsc.rs"
doc = false

[[bin]]
name = "fuzz_timing_wheel"
path = "fuzz_targets/fuzz_timing_wheel.rs"
doc = false
