//! 64-bit coordination identity types.
//!
//! These types form the identity spine for the coordination subsystem: runs,
//! shards, workers, operations, jobs, fence epochs, logical time, and shard
//! lookup keys.  All downstream coordination modules (backend traits, in-memory
//! coordinator, session management) and the deterministic simulation test
//! framework depend on this module.
//!
//! Five of the eight types are mechanically generated by [`define_id_64!`]:
//! [`RunId`], [`ShardId`], [`WorkerId`], [`OpId`], and [`JobId`].  The
//! remaining three ([`FenceEpoch`], [`LogicalTime`], [`ShardKey`]) are
//! hand-written because they carry domain-specific invariants that the
//! macro cannot express.
//!
//! # Type overview
//!
//! | Type | Width | Construction | Purpose |
//! |------|-------|-------------|---------|
//! | [`RunId`] | 8 B | `from_raw` (pub) | Unique run identifier |
//! | [`ShardId`] | 8 B | `from_raw` (pub) | Shard identity within a run |
//! | [`WorkerId`] | 8 B | `from_raw` (pub) | Worker process identity |
//! | [`OpId`] | 8 B | `from_raw` (pub) | Caller-generated idempotency key (CSPRNG) |
//! | [`JobId`] | 8 B | `from_raw` (pub) | Higher-level job grouping |
//! | [`FenceEpoch`] | 8 B | `from_raw` (pub) | Monotonic epoch for leader fencing |
//! | [`LogicalTime`] | 8 B | `from_raw` (pub) | Abstract monotonic clock for leases |
//! | [`ShardKey`] | 16 B | `new(RunId, ShardId)` | Compound HashMap lookup key |
//!
//! # Design rationale: 64-bit width
//!
//! Coordination types use `u64` rather than the `[u8; 32]` width used by
//! content-addressed identity types.  The tradeoff:
//!
//! - **Content-addressed IDs** (`FindingId`, `OccurrenceId`, etc.) derive
//!   from unbounded external inputs and need 256-bit collision resistance.
//! - **Coordination IDs** are counters, assigned identifiers, or lookup keys
//!   with bounded cardinality per run.  A 64-bit width fits in a single
//!   register, halves HashMap key size, and packs 8 values per cache line
//!   — meaningful for high-frequency coordination operations.
//!
//! Types that *derive* coordination values from hashed inputs (e.g., split
//! shard IDs) use [`finalize_64`](super::finalize_64), which truncates a
//! BLAKE3 digest to 64 bits.  See its documentation for cardinality bounds.

use crate::define_id_64;
use crate::identity::CanonicalBytes;

// =========================================================================
// Macro-generated types
// =========================================================================

define_id_64! {
    /// Unique run identifier scoping all shards within a single pipeline execution.
    RunId
}

define_id_64! {
    /// Shard identity within a run; derived (split) shards have bit 63 set.
    ShardId
}

define_id_64! {
    /// Worker (scanner) process identity for lease ownership and owner-divergence checks.
    WorkerId
}

define_id_64! {
    /// Caller-generated idempotency key for replay detection (SHOULD use CSPRNG).
    OpId
}

define_id_64! {
    /// Higher-level job grouping for multi-run lifecycle management.
    JobId
}

impl ShardId {
    /// Returns `true` if bit 63 is set, marking this as a split-derived shard.
    ///
    /// Root shards (externally assigned) have bit 63 clear. Derived shards are
    /// produced by `derive_split_shard_id` (in `gossip-coordination`)
    /// which forces bit 63 high.
    #[inline]
    pub const fn is_derived(&self) -> bool {
        self.0 >> 63 != 0
    }
}

// =========================================================================
// FenceEpoch — hand-written
// =========================================================================

/// Monotonically increasing epoch for leader fencing.
///
/// `FenceEpoch` prevents stale leaders from mutating shard state after a
/// new leader has been elected.  The epoch is incremented on every leader
/// transition; operations bearing an outdated epoch are rejected.
///
/// `increment()` intentionally panics at `u64::MAX` rather than saturating,
/// because a saturating add would silently produce duplicate epochs, breaking
/// mutual exclusion.  See Kleppmann, "How to do distributed locking" (2016);
/// Hochstein, "Fencing Tokens" FizzBee formal model (2025).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct FenceEpoch(u64);

impl ::core::fmt::Debug for FenceEpoch {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        write!(f, "FenceEpoch({})", self.0)
    }
}

impl FenceEpoch {
    /// The zero sentinel -- "no epoch assigned" (pre-registration state).
    pub const ZERO: Self = Self(0);
    /// The first valid epoch (value=1); shard records start here after creation.
    pub const INITIAL: Self = Self(1);

    /// Construct from a raw `u64`.
    #[inline]
    pub const fn from_raw(raw: u64) -> Self {
        Self(raw)
    }

    /// Return the inner `u64`.
    #[inline]
    pub const fn as_raw(&self) -> u64 {
        self.0
    }

    /// Whether an epoch has been assigned (i.e., is not [`ZERO`](Self::ZERO)).
    #[inline]
    pub const fn is_assigned(&self) -> bool {
        self.0 != 0
    }

    /// Advance the epoch by one.
    ///
    /// # Panics
    ///
    /// Panics if the epoch is already `u64::MAX`.  This is intentional:
    /// `saturating_add` would silently produce duplicate epochs, breaking
    /// mutual exclusion.
    #[must_use = "increment returns a new epoch; the original is unchanged"]
    #[inline]
    pub fn increment(&self) -> Self {
        Self(
            self.0
                .checked_add(1)
                .expect("FenceEpoch overflow at u64::MAX"),
        )
    }
}

impl CanonicalBytes for FenceEpoch {
    /// 8-byte little-endian encoding, no length prefix (fixed width).
    #[inline]
    fn write_canonical(&self, h: &mut blake3::Hasher) {
        h.update(&self.0.to_le_bytes());
    }
}

// Compile-time assertions for FenceEpoch sentinels.
const _: () = assert!(FenceEpoch::INITIAL.as_raw() == 1);
const _: () = assert!(FenceEpoch::ZERO.as_raw() == 0);

// =========================================================================
// LogicalTime — hand-written
// =========================================================================

/// Monotonic logical clock for lease expiration and ordering.
///
/// `LogicalTime` is not wall-clock time — it is an abstract, monotonically
/// increasing counter used for lease expiration, Lamport timestamps, and
/// deterministic simulation clocks.
///
/// `checked_add` returns `None` on overflow to prevent immortal leases.
/// See Gray & Cheriton, "Leases: An Efficient Fault-Tolerant Mechanism for
/// Distributed File Cache Consistency" (SOSP 1989).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct LogicalTime(u64);

impl ::core::fmt::Debug for LogicalTime {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        write!(f, "LogicalTime({})", self.0)
    }
}

impl LogicalTime {
    /// The zero sentinel -- origin of time; operations require `now > ZERO`.
    pub const ZERO: Self = Self(0);

    /// Construct from a raw `u64`.
    #[inline]
    pub const fn from_raw(raw: u64) -> Self {
        Self(raw)
    }

    /// Return the inner `u64`.
    #[inline]
    pub const fn as_raw(&self) -> u64 {
        self.0
    }

    /// Advance time by `duration`.
    ///
    /// Returns `None` on overflow to prevent immortal leases.
    #[must_use = "checked_add returns a new time; the original is unchanged"]
    #[inline]
    pub fn checked_add(&self, duration: u64) -> Option<Self> {
        self.0.checked_add(duration).map(Self)
    }
}

impl CanonicalBytes for LogicalTime {
    /// 8-byte little-endian encoding, no length prefix (fixed width).
    #[inline]
    fn write_canonical(&self, h: &mut blake3::Hasher) {
        h.update(&self.0.to_le_bytes());
    }
}

// =========================================================================
// ShardKey — compound lookup type
// =========================================================================

/// Compound HashMap lookup key for the coordinator shard map.
///
/// Combines a [`RunId`] and [`ShardId`] into a single 16-byte key for
/// shard-state lookups. Two shards in different runs may share the same
/// `ShardId`, so the `RunId` component is essential for disambiguation.
///
/// Fields are private with accessors (codebase convention).
///
/// No `Ord` -- this is a lookup key, not an ordered value. Ordering shards
/// by their key range is done via `ShardSpec`, not `ShardKey`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ShardKey {
    run: RunId,
    shard: ShardId,
}

impl ::core::fmt::Debug for ShardKey {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("ShardKey")
            .field("run", &self.run)
            .field("shard", &self.shard)
            .finish()
    }
}

// `Display` intentionally produces the same output as `Debug` so that
// `tracing` span fields using `%` (Display) and `?` (Debug) are
// interchangeable for identity types.
impl ::core::fmt::Display for ShardKey {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        ::core::fmt::Debug::fmt(self, f)
    }
}

impl ShardKey {
    /// Construct a new `ShardKey`.
    #[inline]
    pub const fn new(run: RunId, shard: ShardId) -> Self {
        Self { run, shard }
    }

    /// The run component.
    #[inline]
    pub const fn run(&self) -> RunId {
        self.run
    }

    /// The shard component.
    #[inline]
    pub const fn shard(&self) -> ShardId {
        self.shard
    }
}

impl CanonicalBytes for ShardKey {
    /// Encodes `run || shard` in field order (16 bytes total). Both fields
    /// are fixed-width (8 bytes each), so no length prefix is needed and
    /// the boundary is unambiguous.
    #[inline]
    fn write_canonical(&self, h: &mut blake3::Hasher) {
        self.run.write_canonical(h);
        self.shard.write_canonical(h);
    }
}

// =========================================================================
// Tests
// =========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_util::canonical_digest;
    use proptest::prelude::*;

    // -------------------------------------------------------------------
    // Smoke tests for macro-generated types
    // -------------------------------------------------------------------

    crate::smoke_test_id_64!(RunId, ShardId, WorkerId, OpId, JobId);

    // -------------------------------------------------------------------
    // FenceEpoch
    // -------------------------------------------------------------------

    #[test]
    fn fence_epoch_size() {
        assert_eq!(core::mem::size_of::<FenceEpoch>(), 8);
    }

    #[test]
    fn fence_epoch_increment_from_initial() {
        let epoch = FenceEpoch::INITIAL.increment();
        assert_eq!(epoch.as_raw(), 2);
    }

    #[test]
    fn fence_epoch_increment_from_zero() {
        let epoch = FenceEpoch::ZERO.increment();
        assert_eq!(epoch, FenceEpoch::INITIAL);
    }

    #[test]
    #[should_panic(expected = "FenceEpoch overflow")]
    fn fence_epoch_overflow() {
        let max = FenceEpoch::from_raw(u64::MAX);
        let _ = max.increment();
    }

    #[test]
    fn fence_epoch_debug_format() {
        assert_eq!(format!("{:?}", FenceEpoch::INITIAL), "FenceEpoch(1)");
    }

    // -------------------------------------------------------------------
    // LogicalTime
    // -------------------------------------------------------------------

    #[test]
    fn logical_time_size() {
        assert_eq!(core::mem::size_of::<LogicalTime>(), 8);
    }

    #[test]
    fn logical_time_checked_add_zero() {
        assert_eq!(LogicalTime::ZERO.checked_add(0), Some(LogicalTime::ZERO));
    }

    #[test]
    fn logical_time_checked_add_value() {
        assert_eq!(
            LogicalTime::ZERO.checked_add(42),
            Some(LogicalTime::from_raw(42))
        );
    }

    #[test]
    fn logical_time_checked_add_overflow_from_max() {
        let max = LogicalTime::from_raw(u64::MAX);
        assert_eq!(max.checked_add(1), None);
    }

    #[test]
    fn logical_time_checked_add_overflow_from_one() {
        let one = LogicalTime::from_raw(1);
        assert_eq!(one.checked_add(u64::MAX), None);
    }

    #[test]
    fn logical_time_debug_format() {
        assert_eq!(
            format!("{:?}", LogicalTime::from_raw(99)),
            "LogicalTime(99)"
        );
    }

    // -------------------------------------------------------------------
    // ShardKey
    // -------------------------------------------------------------------

    #[test]
    fn shard_key_construction_and_accessors() {
        let run = RunId::from_raw(1);
        let shard = ShardId::from_raw(2);
        let key = ShardKey::new(run, shard);
        assert_eq!(key.run(), run);
        assert_eq!(key.shard(), shard);
    }

    #[test]
    fn shard_key_equality() {
        let a = ShardKey::new(RunId::from_raw(1), ShardId::from_raw(2));
        let b = ShardKey::new(RunId::from_raw(1), ShardId::from_raw(2));
        let c = ShardKey::new(RunId::from_raw(1), ShardId::from_raw(3));
        let d = ShardKey::new(RunId::from_raw(2), ShardId::from_raw(2));
        assert_eq!(a, b);
        assert_ne!(a, c); // same run, different shard
        assert_ne!(a, d); // different run, same shard
    }

    #[test]
    fn shard_key_debug_format() {
        let key = ShardKey::new(RunId::from_raw(10), ShardId::from_raw(20));
        let dbg = format!("{key:?}");
        assert!(dbg.contains("ShardKey"));
        assert!(dbg.contains("RunId(10)"));
        assert!(dbg.contains("ShardId(20)"));
    }

    // -------------------------------------------------------------------
    // ShardId::is_derived
    // -------------------------------------------------------------------

    #[test]
    fn shard_id_derived_boundary() {
        assert!(!ShardId::from_raw((1u64 << 63) - 1).is_derived());
        assert!(ShardId::from_raw(1u64 << 63).is_derived());
    }

    // -------------------------------------------------------------------
    // FenceEpoch::is_assigned
    // -------------------------------------------------------------------

    #[test]
    fn fence_epoch_is_assigned() {
        assert!(!FenceEpoch::ZERO.is_assigned());
        assert!(FenceEpoch::INITIAL.is_assigned());
        assert!(FenceEpoch::from_raw(u64::MAX).is_assigned());
    }

    // -------------------------------------------------------------------
    // ShardKey — HashMap usability
    // -------------------------------------------------------------------

    #[test]
    fn shard_key_usable_as_hashmap_key() {
        use std::collections::HashMap;
        let key = ShardKey::new(RunId::from_raw(1), ShardId::from_raw(2));
        let mut map = HashMap::new();
        map.insert(key, 42);
        assert_eq!(map.get(&key), Some(&42));
    }

    // -------------------------------------------------------------------
    // CanonicalBytes — property-based (all 8 types)
    // -------------------------------------------------------------------

    proptest! {
        #![proptest_config(crate::test_util::miri_proptest_config())]

        // -- Stability: same input → same digest --------------------------

        #[test]
        fn run_id_canonical_stable(v in any::<u64>()) {
            let id = RunId::from_raw(v);
            prop_assert_eq!(canonical_digest(&id), canonical_digest(&id));
        }

        #[test]
        fn shard_id_canonical_stable(v in any::<u64>()) {
            let id = ShardId::from_raw(v);
            prop_assert_eq!(canonical_digest(&id), canonical_digest(&id));
        }

        #[test]
        fn worker_id_canonical_stable(v in any::<u64>()) {
            let id = WorkerId::from_raw(v);
            prop_assert_eq!(canonical_digest(&id), canonical_digest(&id));
        }

        #[test]
        fn op_id_canonical_stable(v in any::<u64>()) {
            let id = OpId::from_raw(v);
            prop_assert_eq!(canonical_digest(&id), canonical_digest(&id));
        }

        #[test]
        fn job_id_canonical_stable(v in any::<u64>()) {
            let id = JobId::from_raw(v);
            prop_assert_eq!(canonical_digest(&id), canonical_digest(&id));
        }

        #[test]
        fn fence_epoch_canonical_stable(v in any::<u64>()) {
            let e = FenceEpoch::from_raw(v);
            prop_assert_eq!(canonical_digest(&e), canonical_digest(&e));
        }

        #[test]
        fn logical_time_canonical_stable(v in any::<u64>()) {
            let t = LogicalTime::from_raw(v);
            prop_assert_eq!(canonical_digest(&t), canonical_digest(&t));
        }

        #[test]
        fn shard_key_canonical_stable(r in any::<u64>(), s in any::<u64>()) {
            let key = ShardKey::new(RunId::from_raw(r), ShardId::from_raw(s));
            prop_assert_eq!(canonical_digest(&key), canonical_digest(&key));
        }

        // -- Collision-freedom: distinct values → distinct digests --------

        #[test]
        fn run_id_canonical_collision_free(a in any::<u64>(), b in any::<u64>()) {
            prop_assume!(a != b);
            prop_assert_ne!(canonical_digest(&RunId::from_raw(a)), canonical_digest(&RunId::from_raw(b)));
        }

        #[test]
        fn shard_id_canonical_collision_free(a in any::<u64>(), b in any::<u64>()) {
            prop_assume!(a != b);
            prop_assert_ne!(canonical_digest(&ShardId::from_raw(a)), canonical_digest(&ShardId::from_raw(b)));
        }

        #[test]
        fn worker_id_canonical_collision_free(a in any::<u64>(), b in any::<u64>()) {
            prop_assume!(a != b);
            prop_assert_ne!(canonical_digest(&WorkerId::from_raw(a)), canonical_digest(&WorkerId::from_raw(b)));
        }

        #[test]
        fn op_id_canonical_collision_free(a in any::<u64>(), b in any::<u64>()) {
            prop_assume!(a != b);
            prop_assert_ne!(canonical_digest(&OpId::from_raw(a)), canonical_digest(&OpId::from_raw(b)));
        }

        #[test]
        fn job_id_canonical_collision_free(a in any::<u64>(), b in any::<u64>()) {
            prop_assume!(a != b);
            prop_assert_ne!(canonical_digest(&JobId::from_raw(a)), canonical_digest(&JobId::from_raw(b)));
        }

        #[test]
        fn fence_epoch_canonical_collision_free(a in any::<u64>(), b in any::<u64>()) {
            prop_assume!(a != b);
            prop_assert_ne!(canonical_digest(&FenceEpoch::from_raw(a)), canonical_digest(&FenceEpoch::from_raw(b)));
        }

        #[test]
        fn logical_time_canonical_collision_free(a in any::<u64>(), b in any::<u64>()) {
            prop_assume!(a != b);
            prop_assert_ne!(canonical_digest(&LogicalTime::from_raw(a)), canonical_digest(&LogicalTime::from_raw(b)));
        }

        #[test]
        fn shard_key_canonical_collision_free(
            r1 in any::<u64>(), s1 in any::<u64>(),
            r2 in any::<u64>(), s2 in any::<u64>(),
        ) {
            prop_assume!(r1 != r2 || s1 != s2);
            let k1 = ShardKey::new(RunId::from_raw(r1), ShardId::from_raw(s1));
            let k2 = ShardKey::new(RunId::from_raw(r2), ShardId::from_raw(s2));
            prop_assert_ne!(canonical_digest(&k1), canonical_digest(&k2));
        }

        // -- Ordering: derived Ord matches u64 Ord -------------------------

        #[test]
        fn fence_epoch_ordering_consistent(a in any::<u64>(), b in any::<u64>()) {
            prop_assert_eq!(
                FenceEpoch::from_raw(a).cmp(&FenceEpoch::from_raw(b)),
                a.cmp(&b),
            );
        }

        #[test]
        fn logical_time_ordering_consistent(a in any::<u64>(), b in any::<u64>()) {
            prop_assert_eq!(
                LogicalTime::from_raw(a).cmp(&LogicalTime::from_raw(b)),
                a.cmp(&b),
            );
        }

        // -- ShardId::is_derived: bit 63 semantics -------------------------

        #[test]
        fn shard_id_is_derived_iff_bit63_set(v in any::<u64>()) {
            prop_assert_eq!(ShardId::from_raw(v).is_derived(), v >= (1u64 << 63));
        }
    }
}
