//! Proptest state-machine tests for coordination simulation.
//!
//! These tests generate `Vec<SimOp>` sequences via proptest strategies and feed
//! them through [`CoordinationSim::step()`], gaining per-operation shrinking that
//! the seed-based mega-sim tests (which call [`CoordinationSim::run()`]) cannot
//! provide. When a bug is found, proptest minimizes to the smallest failing
//! operation sequence -- immediate causal chain visibility instead of replaying
//! thousands of ops from a seed.
//!
//! # Complementary role with seed-based tests
//!
//! The seed-based mega-sim (`run()`) provides depth: long sequences with implicit
//! fault injection (time jumps, lease expiry, worker pauses) driven by
//! [`FaultConfig`](super::FaultConfig). These proptest tests provide *shrinkability*:
//! shorter sequences where proptest can isolate a minimal failing subsequence. The
//! two approaches cover different failure-finding trade-offs and are not redundant.
//!
//! # Strategy design
//!
//! Operations are generated statelessly (no tracking of held shards, paused workers,
//! etc.). The harness handles rejected/skipped ops gracefully, and the invariant
//! checker runs after every step regardless of outcome. Stateless strategies shrink
//! dramatically better because proptest can remove any op without invalidating the
//! sequence.
//!
//! # Rejection rate
//!
//! Expected ~45-55% rejection for held-shard ops (Checkpoint, Complete, Renew, Park,
//! Split*). Rejections are valuable: they verify the coordinator's rejection path
//! preserves safety. A 50-op sequence with 50% rejection still produces ~25 effective
//! state transitions.
//!
//! # Fault injection
//!
//! `step()` does **not** consult `FaultConfig` -- implicit fault injection (time
//! jumps, lease expiry, worker pauses) only happens inside [`CoordinationSim::run()`].
//! All chaos in these tests is explicit: `AdvanceTime`, `PauseWorker`, and
//! `ResumeWorker` ops generated by [`arb_sim_op`](super::test_util::arb_sim_op).
//! The `FaultLevel` parameter passed to `CoordinationSim::new()` is a required
//! constructor argument but has no runtime effect in `step()`-based tests.
//!
//! # Test tiers
//!
//! | Test | Fault level | Sequence length | Cases | `#[ignore]` | Purpose |
//! |------|-------------|-----------------|-------|-------------|---------|
//! | `prop_short_sequences_preserve_invariants` | SunnyDay | 5..50 | default (256) | no | CI gate |
//! | `prop_safety_under_random_ops` | Stormy | 5..200 | 200 | yes | Deep safety |
//! | `prop_safety_across_fault_levels` | all three | 5..200 | 100 | yes | Level sweep |

use proptest::prelude::*;

use super::FaultLevel;
use super::harness::{CoordinationSim, SimOp};
use super::test_util::{arb_fault_level, arb_sim_op};
use crate::test_util::miri_proptest_config;

/// 4 workers x 8 shards = 32 (worker, shard) pairs.
///
/// This is large enough to create contention (multiple workers targeting the
/// same shard) and diverse state transitions, but small enough that proptest
/// can explore the space in a reasonable number of cases. Increasing beyond
/// this mainly dilutes coverage per case without improving bug-finding power.
const N_WORKERS: u64 = 4;
const N_SHARDS: u64 = 8;

/// Execute a sequence of [`SimOp`]s against a fresh simulation, asserting that
/// no safety invariant (S1--S7) is violated after any individual step.
///
/// # Setup
///
/// Constructs a `CoordinationSim` with [`N_WORKERS`] workers and [`N_SHARDS`]
/// shards, then advances the logical clock past `LogicalTime::ZERO` before
/// running the provided ops. The clock advance is required because the
/// coordinator's lease-deadline computation is undefined at time zero (a lease
/// granted at t=0 with duration D has deadline D, and `is_expired(0, D)` is an
/// ambiguous boundary condition).
///
/// # Failure diagnostics
///
/// On invariant violation, the assertion message includes the seed, fault
/// level, step index, triggering op, resulting event, and the full violation
/// list -- enough context to reproduce without re-running proptest shrinking.
fn run_op_sequence(seed: u64, level: FaultLevel, ops: &[SimOp]) {
    let mut sim = CoordinationSim::new(seed, level).with_workers_and_shards(N_WORKERS, N_SHARDS);

    // Advance clock past ZERO so lease deadlines are well-defined.
    // Uses a fixed offset of 10 ticks (arbitrary, deterministic).
    let (event, violations) = sim.step(SimOp::AdvanceTime { ticks: 10 });
    assert!(
        violations.is_empty(),
        "seed={seed}, level={level:?}: initial AdvanceTime violated invariants: \
         event={event:?}, violations={violations:?}"
    );

    for (i, op) in ops.iter().enumerate() {
        let (event, violations) = sim.step(op.clone());
        assert!(
            violations.is_empty(),
            "seed={seed}, level={level:?}, step={i}, op={op:?}: \
             invariant violation: event={event:?}, violations={violations:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// CI gate: short sequences, no faults, not ignored
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(miri_proptest_config())]

    /// Verify that short random op sequences preserve all safety invariants
    /// (S1--S7) under `SunnyDay` (no injected faults).
    ///
    /// This is the primary CI gate for proptest-based coordination testing.
    /// It runs on every `cargo test` invocation (including under Miri, with
    /// reduced case count via [`miri_proptest_config`]). SunnyDay is used to
    /// keep execution fast; fault-level coverage is handled by the ignored
    /// tests below.
    #[test]
    fn prop_short_sequences_preserve_invariants(
        seed in any::<u64>(),
        ops in proptest::collection::vec(arb_sim_op(N_WORKERS, N_SHARDS), 5..50),
    ) {
        run_op_sequence(seed, FaultLevel::SunnyDay, &ops);
    }
}

// ---------------------------------------------------------------------------
// Deep safety: longer sequences under Stormy faults (ignored, slow)
// ---------------------------------------------------------------------------

#[cfg(not(miri))]
mod deep_safety {
    use super::*;

    proptest! {
        #![proptest_config(proptest::test_runner::Config { cases: 200, ..Default::default() })]

        /// Longer op sequences (up to 200 ops) under `Stormy` fault level,
        /// with per-op shrinking.
        ///
        /// The longer sequences increase the probability of reaching
        /// interesting coordinator states (e.g., all shards acquired then
        /// expired, cascaded splits, park/unpark cycles) that short sequences
        /// rarely explore. `Stormy` is chosen as a middle ground: enough
        /// fault surface to be interesting, but not so aggressive that most
        /// ops are rejected before exercising real state transitions.
        ///
        /// Note: while `FaultLevel::Stormy` is passed to the constructor,
        /// `step()` does not consult `FaultConfig`. The `Stormy` label here
        /// serves as documentation of intent and future-proofs against any
        /// coupling added later.
        ///
        /// Run with: `cargo test --lib -- --ignored prop_safety_under_random_ops`
        #[test]
        #[ignore]
        fn prop_safety_under_random_ops(
            seed in any::<u64>(),
            ops in proptest::collection::vec(arb_sim_op(N_WORKERS, N_SHARDS), 5..200),
        ) {
            run_op_sequence(seed, FaultLevel::Stormy, &ops);
        }
    }
}

// ---------------------------------------------------------------------------
// Fault-level sweep: all three levels x long sequences (ignored, slow)
// ---------------------------------------------------------------------------

#[cfg(not(miri))]
mod fault_sweep {
    use super::*;

    proptest! {
        #![proptest_config(proptest::test_runner::Config { cases: 100, ..Default::default() })]

        /// Explores the fault-level x op-sequence interaction space by
        /// generating all three `FaultLevel` variants alongside long op
        /// sequences.
        ///
        /// While `step()` does not currently consult `FaultConfig`, varying
        /// the fault level across proptest cases exercises the constructor
        /// path for all three levels and guards against regressions if
        /// `step()` ever gains fault-injection awareness. The case count is
        /// lower (100 vs 200) because the three-way level fan-out
        /// effectively triples the exploration budget.
        ///
        /// Run with: `cargo test --lib -- --ignored prop_safety_across_fault_levels`
        #[test]
        #[ignore]
        fn prop_safety_across_fault_levels(
            seed in any::<u64>(),
            level in arb_fault_level(),
            ops in proptest::collection::vec(arb_sim_op(N_WORKERS, N_SHARDS), 5..200),
        ) {
            run_op_sequence(seed, level, &ops);
        }
    }
}
