[package]
name = "gossip-coordination-etcd-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
gossip-coordination-etcd = { path = ".." }
gossip-stdx = { path = "../../gossip-stdx" }

[[bin]]
name = "fuzz_decode_run_record"
path = "fuzz_targets/fuzz_decode_run_record.rs"
doc = false

[[bin]]
name = "fuzz_decode_shard_record"
path = "fuzz_targets/fuzz_decode_shard_record.rs"
doc = false
