[package]
name = "scanner-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "Standalone scanner CLI in gossip-rs workspace"

[dependencies]
gossip-scanner-runtime.workspace = true

[dev-dependencies]
rstest.workspace = true
tempfile = "3"

[[bin]]
name = "scanner-rs"
path = "src/main.rs"
